# Generated by Django 5.2 on 2025-04-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0002_remove_book_genres_remove_book_published_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
